version: '3.8'

services:
  flask-app:
    image: python:3.9
    container_name: flask-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python app.py
