name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository from GitHub
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest  # Run tests using pytest
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      # Step 4: Log in to Docker Hub
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 5: Build Docker image and push to Docker Hub
      - name: Build Docker image and push to Docker Hub
        run: |
          docker build -t mitchbresette/flask-petstore:latest .
          docker push mitchbresette/flask-petstore:latest

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          # SSH into EC2 and pull the latest image from Docker Hub
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.EC2_PRIVATE_KEY }}") ec2-user@${{ secrets.EC2_PUBLIC_IP }} <<EOF
            # Pull the latest Docker image from Docker Hub
            docker pull mitchbresette/flask-petstore:latest
            # Stop any running container (optional)
            docker stop flask-petstore || true
            docker rm flask-petstore || true
            # Run the Docker container
            docker run -d --name flask-petstore -p 5000:5000 mitchbresette/flask-petstore:latest
          EOF
