name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: aws-debian-runner-1

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest  # Run tests using pytest

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t flask-petstore .

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        run: |
          # Ensure Docker is installed and running (if not already done)
          sudo yum update -y
          sudo yum install docker -y
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          
          # Navigate to the project directory
          cd /home/ec2-user/petstore || git clone https://github.com/MitchBresette/FlaskPetStore.git /home/ec2-user/petstore
          
          # Deploy the app using Docker Compose
          cd /home/ec2-user/petstore
          docker-compose up -d
